//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ttcn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADUser()
        {
            this.APSuppliers = new HashSet<APSupplier>();
            this.ARCustomers = new HashSet<ARCustomer>();
            this.ARSaleOrders = new HashSet<ARSaleOrder>();
        }
    
        public int ADUserID { get; set; }
        public string AAStatus { get; set; }
        public int FK_ADUserGroupID { get; set; }
        public string ADUserName { get; set; }
        public string ADPassword { get; set; }
        public Nullable<System.DateTime> AACreatedDate { get; set; }
        public Nullable<System.DateTime> AAUpdatedDate { get; set; }
        public string ADUserResetToken { get; set; }
    
        public virtual ADUserGroup ADUserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APSupplier> APSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCustomer> ARCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARSaleOrder> ARSaleOrders { get; set; }
    }
}
