//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ttcn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APSupplier()
        {
            this.ICProducts = new HashSet<ICProduct>();
        }
    
        public int APSupplierID { get; set; }
        public string AAStatus { get; set; }
        public string AACreatedUser { get; set; }
        public string AAUpdatedUser { get; set; }
        public Nullable<System.DateTime> AACreatedDate { get; set; }
        public Nullable<System.DateTime> AAUpdatedDate { get; set; }
        public int FK_ADUserID { get; set; }
        public string APSupplierNo { get; set; }
        public string APSupplierName { get; set; }
        public string APSupplierAddress { get; set; }
        public string APSupplierStockAddress { get; set; }
        public string APSupplierContactEmail { get; set; }
        public string APSupplierContactPhone { get; set; }
    
        public virtual ADUser ADUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICProduct> ICProducts { get; set; }
    }
}
