//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ttcn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARCustomer()
        {
            this.ARCustomerDeliveryAddressses = new HashSet<ARCustomerDeliveryAddresss>();
        }
    
        public int ARCustomerID { get; set; }
        public string AAStatus { get; set; }
        public string AACreatedUser { get; set; }
        public string AAUpdatedUser { get; set; }
        public Nullable<System.DateTime> AACreatedDate { get; set; }
        public Nullable<System.DateTime> AAUpdatedDate { get; set; }
        public int FK_ADUserID { get; set; }
        public string ARCustomerNo { get; set; }
        public string ARCustomerName { get; set; }
        public Nullable<System.DateTime> ARCustomerBirthDay { get; set; }
        public string ARCustomerAddress { get; set; }
        public string ARCustomerContactEmail { get; set; }
        public string ARCustomerContactPhone { get; set; }
        public Nullable<bool> ARCustomerSex { get; set; }
    
        public virtual ADUser ADUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCustomerDeliveryAddresss> ARCustomerDeliveryAddressses { get; set; }
    }
}
