//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ttcn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCustomerDeliveryAddresss
    {
        public int ARCustomerDeliveryAddressID { get; set; }
        public string AAStatus { get; set; }
        public string AACreatedUser { get; set; }
        public string AAUpdatedUser { get; set; }
        public Nullable<System.DateTime> AACreatedDate { get; set; }
        public Nullable<System.DateTime> AAUpdatedDate { get; set; }
        public string ARCustomerDeliveryAddressReceive { get; set; }
        public string ARCustomerDeliveryAddressContactPhone { get; set; }
        public Nullable<int> FK_ARCustomerID { get; set; }
        public Nullable<int> FK_GEStateProvinceID { get; set; }
        public Nullable<int> FK_GEDistrictID { get; set; }
        public Nullable<int> FK_GEWardID { get; set; }
        public Nullable<int> FK_GEStreetID { get; set; }
    
        public virtual ARCustomer ARCustomer { get; set; }
        public virtual GEDistrict GEDistrict { get; set; }
        public virtual GEStateProvince GEStateProvince { get; set; }
        public virtual GEStreet GEStreet { get; set; }
        public virtual GEWard GEWard { get; set; }
    }
}
