//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ttcn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARFurnitureTypeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARFurnitureTypeGroup()
        {
            this.ARFurnitureTypes = new HashSet<ARFurnitureType>();
            this.ARSaleOrderItems = new HashSet<ARSaleOrderItem>();
        }
    
        public int ARFurnitureTypeGroupID { get; set; }
        public string AAStatus { get; set; }
        public string AACreatedUser { get; set; }
        public string AAUpdatedUser { get; set; }
        public Nullable<System.DateTime> AACreatedDate { get; set; }
        public Nullable<System.DateTime> AAUpdatedDate { get; set; }
        public string ARFurnitureTypeGroupName { get; set; }
        public string ARFurnitureTypeGroupNo { get; set; }
        public string ARFurnitureTypeGroupDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARFurnitureType> ARFurnitureTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARSaleOrderItem> ARSaleOrderItems { get; set; }
    }
}
