//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ttcn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARFurnitureType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARFurnitureType()
        {
            this.ARSaleOrderItems = new HashSet<ARSaleOrderItem>();
            this.ICProducts = new HashSet<ICProduct>();
        }
    
        public int ARFurnitureTypeID { get; set; }
        public string AAStatus { get; set; }
        public string AACreatedUser { get; set; }
        public string AAUpdatedUser { get; set; }
        public Nullable<System.DateTime> AACreatedDate { get; set; }
        public Nullable<System.DateTime> AAUpdatedDate { get; set; }
        public string ARFurnitureTypeName { get; set; }
        public string ARFurnitureTypeNo { get; set; }
        public string ARFurnitureTypeDesc { get; set; }
        public Nullable<int> FK_ARFurnitureTypeGroupID { get; set; }
        public string ARFurnitureTypeImageUrl { get; set; }
    
        public virtual ARFurnitureTypeGroup ARFurnitureTypeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARSaleOrderItem> ARSaleOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICProduct> ICProducts { get; set; }
    }
}
