//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ttcn_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICProduct
    {
        public int ICProductID { get; set; }
        public string AACreatedUser { get; set; }
        public Nullable<System.DateTime> AACreatedDate { get; set; }
        public string AAUpdatedUser { get; set; }
        public Nullable<System.DateTime> AAUpdatedDate { get; set; }
        public string AAStatus { get; set; }
        public Nullable<int> FK_ARFurnitureTypeID { get; set; }
        public Nullable<int> FK_APSupplierID { get; set; }
        public string ICProductNo { get; set; }
        public string ICProductName { get; set; }
        public string ICProductDesc { get; set; }
        public Nullable<bool> ICProductActiveCheck { get; set; }
        public Nullable<decimal> ICProductLength { get; set; }
        public Nullable<decimal> ICProductHeight { get; set; }
        public Nullable<decimal> ICProductWidth { get; set; }
        public Nullable<decimal> ICProductWeight { get; set; }
        public byte[] ICProductPicture { get; set; }
        public Nullable<decimal> ICProductPrice { get; set; }
        public string ICProductComment { get; set; }
        public string ICProductMaterial { get; set; }
        public string ICProductColor { get; set; }
    
        public virtual APSupplier APSupplier { get; set; }
        public virtual ARFurnitureType ARFurnitureType { get; set; }
    }
}
